### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ppavlov-dw** [vuestorefront/salesforce-commerce-cloud#3]
**Open-Source Version**

- [x] Granular API selection per endpoint
- [ ] SFCC-driven locales
- [ ] SFCC-driven currencies
- [ ] Generated TS types from metadata

**Enterprise Version**

- [ ] Content management using Page Designer / Slots / Assets
- [ ] Feature flags and runtime configurations using global and site custom preferences
- [ ] Database storage using custom objects and generic mappings
- [ ] SEO functionalities using the SFCC sitemaps, page URL configurations and Page Meta Tags tool
- [ ] Email delivery
- [ ] Product recommendations driven by Einstein
- [ ] Customs segmentation
- [ ] Gift cards

**Core Improvements**

- [ ] Product sets
- [ ] Product bundles
- [ ] Product options
